# top level stuff you probably don't need to touch
highlighter: rouge
permalink: /:title
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://santigarcor.me
baseurl: /
title: Santiago García
author: Santiago García
name: Santiago García
description: Personal page and resume
avatar: profile.png
website: santigarcor.me
email: santiago@santigarcor.me
email_full: mailto:santiago@santigarcor.me
github: santigarcor # username
twitter: santigarcor
linkedin: santigarcor
google_maps: 'https://www.google.com.co/maps/place/Medell%C3%ADn,+Antioquia/@6.2686734,-75.6664326,12z/data=!3m1!4b1!4m5!3m4!1s0x8e4428ef4e52dddb:0x722fd6c39270ac72!8m2!3d6.244203!4d-75.5812119?hl=es-419'
city: Medellín
country: Colombia
#stackoverflow: santigarcor   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: santigarcorme
google_analytics: UA-84408499-2


# needed for travis-ci build
exclude: [vendor]

t:
  en:
    blog:
      name: 'BLOG'
      url: 'blog-en'
    projects:
      name: 'PROJECTS'
      url: 'projects'
    # resume:
    #   name: 'RESUME'
    #   url: 'resume'
  es:
    blog:
      name: 'BLOG'
      url: 'blog-es'
    projects:
      name: 'PROYECTOS'
      url: 'proyectos'
    # resume:
    #   name: 'CURRÍCULUM'
    #   url: 'cv'