# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://santigarcor.me
baseurl: /
title: Santiago García
author: Santiago García
description: Personal page and resume
avatar: profile.png
email: yourname@email.com
github: santigarcor # username
twitter: santigarcor
linkedin: santigarcor
#stackoverflow: santigarcor   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: santigarcorme
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
